import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */
export const products = [
  {
    _id: "912f0ce7-e6fd-4e4b-bb00-9b62449f30c0",
    badge: "Trending",
    img: "/img/feature1.jpg",
    title: "Black Hoodie",
    discountPrice: "500",
    description: "Men Black Printed Cotton Pure Cotton T-shirt",
    price: "1000",
    offerPercent: "50% OFF",
    category: "Tshirt",
    ratings: "3.5",
    id: "1",
  },
  {
    _id: uuid(),
    badge: "",
    title: "Roadster",
    description: "Men White Printed Cotton Pure Cotton T-shirt",
    img: "https://assets.myntassets.com/h_720,q_90,w_540/v1/assets/images/2475811/2018/4/20/11524206887970-Roadster-Men-Tshirts-9291524206887825-2.jpg",
    price: "599",
    discountPrice: "269",
    category: "Tshirt",
    offerPercent: "52% off",
    ratings: "4.2",
    id: "16",
  },
  {
    _id: uuid(),
    badge: "",
    title: "HERE&NOW",
    description: "Varsity Printed Pure Cotton T-shirt",
    img: "https://assets.myntassets.com/h_720,q_90,w_540/v1/assets/images/21982472/2023/2/27/812c0298-2549-4d7e-bb1e-183c1c3b81461677475821822-HERENOW-Men-Tshirts-7701677475821300-1.jpg",
    price: "599",
    discountPrice: "239",
    category: "Tshirt",
    offerPercent: "53% off",
    ratings: "3.5",
    id: "17",
  },
  {
    _id: uuid(),
    badge: "",
    title: "KETCH",
    description: "Men Black Slim Fit Gingham Checks Checked Casual Shirt",
    img: "https://assets.myntassets.com/h_720,q_90,w_540/v1/assets/images/16696354/2022/1/5/e3051c16-3f7f-45cf-9ae6-a8ebafd74e931641387641450KETCHMenBlackSlimFitTartanChecksCheckedCasualShirt1.jpg",
    price: "999",
    discountPrice: "399",
    category: "Tshirt",
    offerPercent: "55% off",
    ratings: "4.5",
    id: "15",
  },
  {
    _id: uuid(),
    badge: "",
    title: "HIGHLANDER",
    description: "Men White & Red Slim Fit Printed Casual Shirt",
    img: "https://assets.myntassets.com/h_720,q_90,w_540/v1/assets/images/productimage/2021/4/8/83b64237-b332-47c6-99ef-283823a8312a1617887077149-1.jpg",
    price: "1099",
    discountPrice: "439",
    offerPercent: "60% off",
    category: "Tshirt",
    ratings: "2.0",
  },
  {
    _id: "84d3c8cf-3374-4e61-a37f-7ce16f0dff28",
    badge: "Trending",
    img: "/img/feature3.png",
    title: "Wrist Watch",
    discountPrice: "1000",
    price: "1500",
    offerPercent: "50% OFF",
    category: "Acessories",
    ratings: "4.5",
    id: "2",
  },
  {
    _id: "eca1bb08-f501-4bd0-85cf-b9355cf4ba58",
    badge: "Trending",
    img: "/img/feature4.jpg",
    title: "Pen Drive",
    discountPrice: "300",
    price: "600",
    offerPercent: "50% OFF",
    category: "Acessories",
    ratings: "5",
    id: "3",
  },
  {
    _id: "8d4482b6-9ef0-40dd-852d-9f93dc9b3caf",
    badge: "Trending",
    img: "/img/feature5.jpeg",
    title: "Pair of Socks",
    discountPrice: "1500",
    price: "2000",
    offerPercent: "50% OFF",
    category: "Acessories",
    ratings: "2",
    id: "4",
  },
  {
    _id: "8262ae01-af15-4b2f-bc31-5b9eb176027e",
    badge: "Trending",
    img: "/img/feature6.jpg",
    title: "Stickers Pack",
    discountPrice: "1500",
    price: "2500",
    offerPercent: "50% OFF",
    category: "Toys",
    ratings: "1",
    id: "5",
  },
  {
    _id: "615f462e-f0e3-403e-ab8e-f858a314872b",
    badge: "Trending",
    img: "/img/feature8.jpg",
    title: " Women Hand Bag",
    discountPrice: "500",
    price: "1000",
    offerPercent: "50% OFF",
    category: "Acessories",
    ratings: "1.5",
    id: "6",
  },
  {
    _id: "138af62e-e2bb-4c08-b17d-aaad19e441fe",
    badge: "Trending",
    img: "/img/feature10.jpg",
    title: " Mini Toys Pack",
    discountPrice: "500",
    price: "1000",
    offerPercent: "50% OFF",
    category: "Acessories",
    ratings: "3.5",
    id: "7",
  },
];
// export const products = [
//   {
//     _id: uuid(),
//     badge: "Trending",
//     img: "/img/feature1.jpg",
//     title: "Black Hoodie",
//     discountPrice: "500",
//     price: "1000",
//     offerPercent: "50% OFF",
//     category: "Tshirt",
//     ratings: "3.5",
//   },
//   {
//     _id: uuid(),
//     badge: "Trending",
//     img: "/img/feature3.png",
//     title: "Wrist Watch",
//     discountPrice: "1000",
//     price: "1500",
//     offerPercent: "50% OFF",
//     category: "Acessories",
//     ratings: "4.5",
//   },
//   {
//     _id: uuid(),
//     badge: "Trending",
//     img: "/img/feature4.jpg",
//     title: "Pen Drive",
//     discountPrice: "300",
//     price: "600",
//     offerPercent: "50% OFF",
//     category: "Acessories",
//     ratings: "5",
//   },
//   {
//     _id: uuid(),
//     badge: "Trending",
//     img: "/img/feature5.jpeg",
//     title: "Pair of Socks",
//     discountPrice: "1500",
//     price: "2000",
//     offerPercent: "50% OFF",
//     category: "Acessories",
//     ratings: "2",
//   },
//   {
//     _id: uuid(),
//     badge: "Trending",
//     img: "/img/feature6.jpg",
//     title: "Stickers Pack",
//     discountPrice: "1500",
//     price: "2500",
//     offerPercent: "50% OFF",
//     category: "Toys",
//     ratings: "1",
//   },
//   {
//     _id: uuid(),
//     badge: "Trending",
//     img: "/img/feature8.jpg",
//     title: " Women Hand Bag",
//     discountPrice: "500",
//     price: "1000",
//     offerPercent: "50% OFF",
//     category: "Acessories",
//     ratings: "1.5",
//   },
//   {
//     _id: uuid(),
//     badge: "Trending",
//     img: "/img/feature10.jpg",
//     title: " Mini Toys Pack",
//     discountPrice: "500",
//     price: "1000",
//     offerPercent: "50% OFF",
//     category: "Acessories",
//     ratings: "3.5",
//   },
// ];
// export const products = [
//   {
//     _id: uuid(),
//     img: "https://rukminim1.flixcart.com/image/612/612/kwxv98w0/book/l/z/y/do-epic-shit-original-imag9gcfcwfvwtep.jpeg?q=70",
//     name: "Do Epic Shit",
//     author: "Ankur Warikoo",
//     price: 219,
//     originalPrice: 399,
//     isBestSeller: true,
//     category: "Self Help",
//     rating: 4.6,
//   },
//   {
//     _id: uuid(),
//     img: "https://rukminim1.flixcart.com/image/612/612/jpu324w0/book/0/9/0/believe-in-yourself-original-imafbzz2h7yfg5zz.jpeg?q=70",
//     name: "Believe In Yourself",
//     author: "Joseph",
//     price: 250,
//     originalPrice: 1200,
//     isBestSeller: false,
//     category: "Self Help",
//     rating: 4,
//   },

//   {
//     _id: uuid(),
//     img: "https://rukminim1.flixcart.com/image/612/612/kokdci80/regionalbooks/t/x/c/zero-to-one-original-imag2zzngtfasecu.jpeg?q=70",
//     name: "Zero To One",
//     author: "Peter Thiel",
//     price: 50,
//     originalPrice: 500,
//     isBestSeller: false,
//     category: "Fiction",
//     rating: 2,
//   },
//   {
//     _id: uuid(),
//     img: "https://rukminim1.flixcart.com/image/612/612/kufuikw0/book/x/s/w/atomic-habits-original-imag7kbzg2fu8rjv.jpeg?q=70",
//     name: "Atomic Habits",
//     author: "James Clear",
//     price: 390,
//     originalPrice: 790,
//     isBestSeller: true,
//     category: "Self Help",
//     rating: 4.8,
//   },

//   {
//     _id: uuid(),
//     img: "https://rukminim1.flixcart.com/image/612/612/kufuikw0/book/0/6/q/ikigai-original-imag7kc7q5ugy2km.jpeg?q=70",
//     name: "IKIGAI",
//     author: "Hector Garcia",
//     price: 600,
//     originalPrice: 1500,
//     isBestSeller: false,
//     category: "Non Fiction",
//     rating: 4,
//   },
//   {
//     _id: uuid(),
//     img: "https://rukminim1.flixcart.com/image/612/612/kgwld3k0/book/1/9/4/rich-dad-poor-dad-original-imafxf885pytvycy.jpeg?q=70",
//     name: "Rich Dad Poor Dad",
//     author: "Robert Kiyoski",
//     price: 350,
//     originalPrice: 500,
//     isBestSeller: false,
//     category: "Non Fiction",
//     rating: 2,
//   },
//   {
//     _id: uuid(),
//     img: "https://rukminim1.flixcart.com/image/612/612/kirr24w0-0/book/k/k/g/the-monk-who-sold-his-ferrari-original-imafyhgacv9jrgv7.jpeg?q=70",
//     name: "Monk Who Sold His Ferrari",
//     author: "Robin Sharma",
//     price: 119,
//     originalPrice: 249,
//     isBestSeller: false,
//     category: "Non Fiction",
//     rating: 3,
//   },
//   {
//     _id: uuid(),
//     img: "https://rukminim1.flixcart.com/image/612/612/ki96c280-0/book/3/p/n/one-indian-girl-original-imafy2zrymfbtygz.jpeg?q=70",
//     name: "One Indian Girl",
//     author: "Chetan Bhagat",
//     price: 157,
//     originalPrice: 195,
//     isBestSeller: false,
//     category: "Fiction",
//     rating: 3,
//   },
//   {
//     _id: uuid(),
//     img: "https://rukminim1.flixcart.com/image/612/612/kjbr8280-0/book/z/r/9/learning-how-to-fly-original-imafyx6zuhvfhv94.jpeg?q=70",
//     name: "Learning How To Fly",
//     author: "A.P.J Abdul Kalam",
//     price: 163,
//     originalPrice: 205,
//     isBestSeller: false,
//     category: "Fiction",
//     rating: 2.5,
//   },
//   {
//     _id: uuid(),
//     img: "https://rukminim1.flixcart.com/image/612/612/kwpam4w0/book/r/a/r/-original-imag9bv6bzstsjgk.jpeg?q=70",
//     name: "400 Days",
//     author: "Chetan Bhagat",
//     price: 699,
//     originalPrice: 999,
//     isBestSeller: false,
//     category: "Self Help",
//     rating: 4,
//   },
//   {
//     _id: uuid(),
//     img: "https://rukminim1.flixcart.com/image/612/612/khxqt8w0-0/book/x/o/v/attitude-is-everything-change-your-attitude-change-your-life-original-imafxtvesfbk8rje.jpeg?q=70",
//     name: "Attitude Is Everything",
//     author: "Keller Jeff",
//     price: 399,
//     originalPrice: 699,
//     isBestSeller: false,
//     category: "Self Help",
//     rating: 3.5,
//   },
//   {
//     _id: uuid(),
//     img: "https://rukminim1.flixcart.com/image/612/612/kufuikw0/book/p/3/d/man-s-search-for-meaning-original-imag7kerxrpweqj9.jpeg?q=70",
//     name: "Man's Search For Meaning",
//     author: "Franky Viktor",
//     price: 243,
//     originalPrice: 349,
//     isBestSeller: false,
//     category: "Non Fiction",
//     rating: 1,
//   },
// ];
